### ISSUE TITLE
doesn't allow asserting belongs to with custom source

### ISSUE THREAD

**Issue by cbortz** [synchronal/schema_assertions#4]
Given a schema:

```elixir
defmodule Group do
  schema "groups" do
    belongs_to :org, Org, source: :organization_id
  end
end
```

The following test will fail:

```elixir
test "schema" do
  assert_belongs_to Group, :org, Org
end
```

...with the message:

```
 Expected Group to belong to
   :org
 via
   .Org

 org_id does not exist in table
```

This is true that `org_id` is not a field. It's an alias for `organization_id`, but it would be nice if I could specify a source in the assertion.

---

I did some sleuthing and looked at the [schema reflection ](https://hexdocs.pm/ecto/Ecto.Schema.html#module-reflection) and saw that the `:owner_key` is set to `:org_id` by Ecto. It doesn't seem like a bug because everything works as you would expect in the actual code.

However that reflection doesn't give us access to the `source`. I did find the reflection `:field_source` which looks something like:

```elixir
Group.__schema__(:field_source, :org_id) # returns :organization_id
```

Checking the reflection of the field source for `:org_id` gives us the value `:organization_id` which is exactly what we're looking for. I wonder if we could leverage this in connection with an optional `:source` option in the `assert_belongs_to` call such that when it is provided we check for a field source alias here: https://github.com/synchronal/schema_assertions/blob/a4c8f2d564677176f3d8e9f675b25ee91982130f/lib/schema_assertions/schema.ex#L9-L14

What do y'all think? If you like this idea, I can open a PR for it.

**Comment by sax** [comment]
@cbortz sorry this took so long to review. I completely missed it somehow.

I made one small addition, which was to define a type for the opts. Just release it as v0.5.0.

**Comment by cbortz** [comment]
@sax No worries. Appreciate the release!
